[metadata]
name = tgfserver
version = 1.4.2
summary = A linux backend application for the operations of the UCSC TGF group.
home_page = https://github.com/JSheare/tgfserver
author = Jacob Shearer
author_email = jacob.shearer6912@gmail.com

[options]
packages = 
	tgfserver
    tgfserver/config
    tgfserver/helpers
	tgfserver/services
	tgfserver/startup
    tgfserver/utilities
    tgfserver/validation
python_requires = >=3.12
install_requires =
    aiohttp
    argon2_cffi
    beautifulsoup4
    cachetools
    cron_converter
    google-api-python-client
    google-auth-httplib2
    google-auth-oauthlib
    playwright
	psutil
    psycopg[binary,pool]
    pydantic

[options.entry_points]
console_scripts =
    tgfserver = tgfserver.main:main

[options.package_data]
tgfserver =
    config/tgfserver.ini
	